stateDiagram-v2
    direction TB
    
    [*] --> qInicio
    
    %% INÍCIO E CASCATA DE ZEROS
    qInicio --> qMilhar_M : M / ε
    qInicio --> qCentena_C : C / ε
    qInicio --> qCentena_D : D / ε
    qInicio --> qDezena_X : X / ε
    qInicio --> qDezena_L : L / ε
    qInicio --> qUnidade_I : I / ε
    qInicio --> qUnidade_V : V / ε
    
    qCentena --> qDezena : ε / "0"
    qDezena --> qUnidade : ε / "0"
    qUnidade --> qFinal : ε / "0"

    %% MILHARES
    state Milhares {
        qMilhar_M --> qMilhar_2M : M / ε
        qMilhar_2M --> qMilhar_3M : M / ε
        
        qMilhar_M --> qCentena : ε / "1"
        qMilhar_2M --> qCentena : ε / "2"
        qMilhar_3M --> qCentena : ε / "3"
    }
    
    %% TRANSIÇÕES MILHARES -> CENTENAS
    qMilhar_M --> qCentena_C : C / "1"
    qMilhar_M --> qCentena_D : D / "1"
    qMilhar_2M --> qCentena_C : C / "2"
    qMilhar_2M --> qCentena_D : D / "2"
    qMilhar_3M --> qCentena_C : C / "3"
    qMilhar_3M --> qCentena_D : D / "3"

    %% CENTENAS
    state Centenas {
        qCentena_C --> qCentena_2C : C / ε
        qCentena_2C --> qCentena_3C : C / ε
        qCentena_C --> qCentena_CD : D / ε
        qCentena_C --> qCentena_CM : M / ε
        qCentena_D --> qCentena_6D : C / ε
        qCentena_6D --> qCentena_7D : C / ε
        qCentena_7D --> qCentena_8D : C / ε
        
        qCentena_C --> qDezena : ε / "1"
        qCentena_2C --> qDezena : ε / "2"
        qCentena_3C --> qDezena : ε / "3"
        qCentena_CD --> qDezena : ε / "4"
        qCentena_D --> qDezena : ε / "5"
        qCentena_6D --> qDezena : ε / "6"
        qCentena_7D --> qDezena : ε / "7"
        qCentena_8D --> qDezena : ε / "8"
        qCentena_CM --> qDezena : ε / "9"
    }

    %% TRANSIÇÕES CENTENAS -> DEZENAS
    qCentena_C --> qDezena_X : X / "1"
    qCentena_C --> qDezena_L : L / "1"
    qCentena_2C --> qDezena_X : X / "2"
    qCentena_CD --> qDezena_X : X / "4"
    qCentena_D --> qDezena_X : X / "5"
    qCentena_CM --> qDezena_X : X / "9"

    %% DEZENAS
    state Dezenas {
        qDezena_X --> qDezena_2X : X / ε
        qDezena_2X --> qDezena_3X : X / ε
        qDezena_X --> qDezena_XL : L / ε
        qDezena_X --> qDezena_XC : C / ε
        qDezena_L --> qDezena_6L : X / ε
        qDezena_6L --> qDezena_7L : X / ε
        qDezena_7L --> qDezena_8L : X / ε

        qDezena_X --> qUnidade : ε / "1"
        qDezena_2X --> qUnidade : ε / "2"
        qDezena_3X --> qUnidade : ε / "3"
        qDezena_XL --> qUnidade : ε / "4"
        qDezena_L --> qUnidade : ε / "5"
        qDezena_6L --> qUnidade : ε / "6"
        qDezena_7L --> qUnidade : ε / "7"
        qDezena_8L --> qUnidade : ε / "8"
        qDezena_XC --> qUnidade : ε / "9"
    }

    %% TRANSIÇÕES DEZENAS -> UNIDADES
    qDezena_X --> qUnidade_I : I / "1"
    qDezena_X --> qUnidade_V : V / "1"
    qDezena_2X --> qUnidade_I : I / "2"
    qDezena_XL --> qUnidade_I : I / "4"
    qDezena_L --> qUnidade_I : I / "5"
    qDezena_XC --> qUnidade_I : I / "9"

    %% UNIDADES
    state Unidades {
        qUnidade_I --> qUnidade_2I : I / ε
        qUnidade_2I --> qUnidade_3I : I / ε
        
        qUnidade_V --> qUnidade_6V : I / ε
        qUnidade_6V --> qUnidade_7V : I / ε
        qUnidade_7V --> qUnidade_8V : I / ε
        
        qUnidade_I --> qFinal : V / "4"
        qUnidade_I --> qFinal : X / "9"

        qUnidade_I --> qFinal : ε / "1"
        qUnidade_2I --> qFinal : ε / "2"
        qUnidade_3I --> qFinal : ε / "3"
        qUnidade_V --> qFinal : ε / "5"
        qUnidade_6V --> qFinal : ε / "6"
        qUnidade_7V --> qFinal : ε / "7"
        qUnidade_8V --> qFinal : ε / "8"
    }
    
    qFinal --> [*]